-- 2022년 1월의 카테고리 별 도서 판매량을 합산
-- 카테고리, 총 판매량 리스트를 출력
-- 카테고리명을 기준으로 오름차순 정렬
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK B
LEFT JOIN BOOK_SALES BS
    ON B.BOOK_ID = BS.BOOK_ID
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;
