-- 부모의 형질을 모두 보유한 대장균의 ID, 대장균의 형질, 부모 대장균의 형질을 출력
-- ID에 대해 오름차순 정렬
SELECT E1.ID, E1.GENOTYPE, E2.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA E1
INNER JOIN ECOLI_DATA E2
    ON E1.PARENT_ID = E2.ID
WHERE E1.GENOTYPE & E2.GENOTYPE = E2.GENOTYPE
ORDER BY E1.ID ASC;
